# fly.toml app configuration file generated for simon-phonebook-backend on 2023-05-09T04:15:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "simon-phonebook-backend"
primary_region = "yyz"

[env]
  PORT = "8080"
  app = "simon-phonebook-backend"
  primary_region = "yyz"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
